name: Build, Test and Push to Docker Hub

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch: {}

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Set up Python (for tests)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 3) Install runtime dependencies
      - name: Install app dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      # 4) Install test dependencies (separate file)
      - name: Install test dependencies
        run: |
          if [ -f requirements-test.txt ]; then
            pip install -r requirements-test.txt
          fi

      # 5) Run pytest as "basic tests"
      - name: Run tests
        run: PYTHONPATH=. pytest -q

      # 6) Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 7) Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 8) Build and push Docker image to Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/doc-api:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/doc-api:${{ github.sha }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      # 5) Deploy: force ECS to pull new image
      - name: Force new ECS deployment
        run: |
          aws ecs update-service \
            --cluster doc-api-cluster \
            --service doc-api-service \
            --force-new-deployment
